"""1:1 port of features/rule_generator/ui.py:_generate_rules_with_comprehensive_engine.

Imports the existing rule_generator.engine + report modules directly (they are
Streamlit-free), so the rule output is literally identical to the Streamlit app.
"""
from __future__ import annotations

import json
import logging
import time
from typing import Any, Callable, Dict, List, Optional

import pandas as pd

# Import from the engine module file directly to avoid features/rule_generator/__init__.py
# which imports the Streamlit UI module.
import importlib.util as _imp
import sys as _sys
from pathlib import Path as _Path

_engine_path = _Path(__file__).resolve().parents[3] / "features" / "rule_generator" / "engine.py"
_spec = _imp.spec_from_file_location("_rg_engine", str(_engine_path))
_engine = _imp.module_from_spec(_spec)
_sys.modules["_rg_engine"] = _engine
_spec.loader.exec_module(_engine)

deep_scan_rule_sheet = _engine.deep_scan_rule_sheet
enrich_dataframe_regex_patterns = _engine.enrich_dataframe_regex_patterns
extract_comprehensive_metadata = _engine.extract_comprehensive_metadata
generate_comprehensive_ai_prompt = _engine.generate_comprehensive_ai_prompt
post_process_rules = _engine.post_process_rules
validate_all_rules = _engine.validate_all_rules

from .azure_openai_config import AzureOpenAIConfig

logger = logging.getLogger(__name__)


def generate_rules_with_comprehensive_engine(
    file_path: Optional[str],
    sheet_name: Optional[str],
    header_row: int,
    df: pd.DataFrame,
    progress_cb: Optional[Callable[[Dict[str, Any]], None]] = None,
) -> pd.DataFrame:
    """Verbatim port of features/rule_generator/ui.py:_generate_rules_with_comprehensive_engine.

    Differences from Streamlit version:
      - st.progress / st.empty are replaced with an optional progress callback.
      - Errors are logged + a fallback rule appended (same behaviour).
    """
    from openai import AzureOpenAI

    client = AzureOpenAI(
        api_version=AzureOpenAIConfig.AZURE_OPENAI_API_VERSION,
        azure_endpoint=AzureOpenAIConfig.AZURE_OPENAI_ENDPOINT,
        api_key=AzureOpenAIConfig.AZURE_OPENAI_KEY,
    )

    # Step 1: Deep scan Excel sheet (only if Excel file)
    column_rules: Dict[str, str] = {}
    if file_path and sheet_name and (file_path.endswith(".xlsx") or file_path.endswith(".xls")):
        column_rules = deep_scan_rule_sheet(file_path, sheet_name, header_row)

    all_rules: List[Dict[str, Any]] = []
    total_cols = len(df.columns)
    all_column_names = [str(c) for c in df.columns]

    for idx, column_name in enumerate(df.columns):
        try:
            if progress_cb:
                progress_cb({
                    "stage": "analyzing",
                    "index": idx + 1, "total": total_cols, "column": str(column_name),
                })

            rule_text = column_rules.get(column_name, None)
            rule_source = "Rules from Existing Sheet" if rule_text else "Generated by AI"

            metadata = extract_comprehensive_metadata(column_name, rule_text)
            # Deterministic sample: dedupe + sort + cap at 50 unique non-null
            # values so identical input data produces an identical prompt
            # regardless of upstream row order.
            sample_data = sorted(
                {str(v) for v in df[column_name].dropna().tolist()}
            )[:50]
            data_type = str(df[column_name].dtype)
            null_pct = (df[column_name].isnull().sum() / len(df)) * 100 if len(df) > 0 else 0
            unique_pct = (df[column_name].nunique() / len(df)) * 100 if len(df) > 0 else 0

            prompt = generate_comprehensive_ai_prompt(
                column_name=column_name,
                sample_data=sample_data,
                data_type=data_type,
                null_pct=null_pct,
                unique_pct=unique_pct,
                metadata=metadata,
                rule_source=rule_source,
                all_columns=all_column_names,
            )

            # temperature=0 + fixed seed + json_object response_format pin the
            # model to deterministic, parseable output across reruns.
            response = client.chat.completions.create(
                model=AzureOpenAIConfig.AZURE_OPENAI_DEPLOYMENT,
                messages=[
                    {"role": "system", "content": "You are a data quality expert. Return only valid JSON."},
                    {"role": "user", "content": prompt},
                ],
                temperature=0,
                seed=42,
                response_format={"type": "json_object"},
                max_tokens=1500,
            )

            response_text = response.choices[0].message.content.strip()

            if response_text.startswith("```"):
                response_text = response_text.split("```")[1]
                if response_text.startswith("json"):
                    response_text = response_text[4:]
                response_text = response_text.strip()

            result = json.loads(response_text)

            if "rules" in result:
                processed_rules = post_process_rules(result["rules"], metadata)
                for rule in processed_rules:
                    all_rules.append({
                        "S.No": len(all_rules) + 1,
                        "Column": column_name,
                        "Business Field": column_name,
                        "Rule Source": rule_source,
                        "Dimension": rule.get("dimension", "Validity"),
                        "Data Quality Rule": rule.get("data_quality_rule", rule.get("rule_statement", "")),
                        "Regex Pattern": (rule.get("regex_pattern") or ""),
                        "Issues Found": rule.get("issues_found", 0),
                        "Issues Found Example": rule.get("issues_found_example", "All values valid - No issues found"),
                    })

            time.sleep(1.0)

        except Exception as exc:
            logger.error("Error processing column '%s': %s", column_name, exc)
            all_rules.append({
                "S.No": len(all_rules) + 1,
                "Column": column_name,
                "Business Field": column_name,
                "Rule Source": "Generated by AI",
                "Dimension": "Validity",
                "Data Quality Rule": f"{column_name} should be validated",
                "Regex Pattern": "",
                "Issues Found": 0,
                "Issues Found Example": f"Error: {exc}",
            })

    validation_df = pd.DataFrame(all_rules)
    return validation_df


def generate_complete(
    file_path: Optional[str],
    sheet_name: Optional[str],
    header_row: int,
    df: pd.DataFrame,
    progress_cb: Optional[Callable[[Dict[str, Any]], None]] = None,
) -> pd.DataFrame:
    """Full end-to-end pipeline matching the Streamlit button click:
    1) generate rules via comprehensive engine
    2) validate against actual data
    3) enrich regex patterns
    """
    df_rules = generate_rules_with_comprehensive_engine(
        file_path, sheet_name, header_row, df, progress_cb,
    )
    df_rules = validate_all_rules(df, df_rules)
    df_rules = enrich_dataframe_regex_patterns(df_rules)
    return df_rules
