import { useEffect, useMemo, useState } from 'react';
import {
  Box, Stack, Button, Typography, Alert, LinearProgress, Grid, Paper, Chip,
  Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Divider,
} from '@mui/material';
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';
import RefreshIcon from '@mui/icons-material/Refresh';
import DeleteIcon from '@mui/icons-material/Delete';
import DownloadIcon from '@mui/icons-material/Download';
import api from '../api.js';
import PageHeader from '../components/PageHeader.jsx';
import EmptyState from '../components/EmptyState.jsx';
import { useDataset } from '../context/DatasetContext.jsx';

const DIMENSION_BG = {
  Accuracy: '#dbeafe', Completeness: '#dcfce7', Consistency: '#fef3c7',
  Validity: '#fce7f3', Uniqueness: '#f3e8ff', Timeliness: '#ccfbf1',
  Integrity: '#fee2e2', Conformity: '#e0e7ff', Reliability: '#ffedd5',
  Relevance: '#ecfccb', Precision: '#fae8ff', Accessibility: '#e0f2fe',
  'Character Length': '#fef3c7',
};
const DIMENSION_FG = {
  Accuracy: '#1e40af', Completeness: '#166534', Consistency: '#92400e',
  Validity: '#9d174d', Uniqueness: '#6b21a8', Timeliness: '#0f766e',
  Integrity: '#991b1b', Conformity: '#3730a3', Reliability: '#9a3412',
  Relevance: '#3f6212', Precision: '#86198f', Accessibility: '#075985',
  'Character Length': '#92400e',
};

function MetricCard({ label, value }) {
  return (
    <Paper sx={{ p: 2.5, textAlign: 'center', borderRadius: 2.5 }}>
      <Typography variant="caption" sx={{
        color: 'text.secondary', textTransform: 'uppercase', letterSpacing: 1, fontWeight: 500,
      }}>{label}</Typography>
      <Typography sx={{ fontSize: '1.8rem', fontWeight: 700, color: 'primary.main', mt: 0.75 }}>
        {value}
      </Typography>
    </Paper>
  );
}

export default function RuleGenerator() {
  const { state } = useDataset();
  const [llm, setLlm] = useState(null);
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState('');
  const [generated, setGenerated] = useState(false);
  const [rules, setRules] = useState([]);
  const [stats, setStats] = useState({ total_rules: 0, columns_covered: 0, dq_dimensions: 0 });

  useEffect(() => {
    api.get('/rule-generator/llm-status').then((r) => setLlm(r.data)).catch(() => setLlm({ configured: false }));
    if (state.loaded) {
      api.get('/rule-generator/rules').then((r) => {
        if (r.data.generated) {
          setRules(r.data.rules);
          setStats({
            total_rules: r.data.total_rules,
            columns_covered: r.data.columns_covered,
            dq_dimensions: r.data.dq_dimensions,
          });
          setGenerated(true);
        }
      }).catch(() => {});
    }
  }, [state.loaded]);

  const generate = async () => {
    setBusy(true); setErr('');
    try {
      const { data } = await api.post('/rule-generator/generate');
      setRules(data.rules);
      setStats({
        total_rules: data.total_rules,
        columns_covered: data.columns_covered,
        dq_dimensions: data.dq_dimensions,
      });
      setGenerated(true);
    } catch (e) { setErr(e?.response?.data?.detail || 'Generation failed'); }
    finally { setBusy(false); }
  };

  const regenerate = async () => {
    setBusy(true); setErr('');
    try {
      await api.post('/rule-generator/regenerate');
      setGenerated(false);
      setRules([]);
      setStats({ total_rules: 0, columns_covered: 0, dq_dimensions: 0 });
    } catch (e) { setErr(e?.response?.data?.detail || 'Failed'); }
    finally { setBusy(false); }
  };

  const clear = async () => {
    setBusy(true); setErr('');
    try {
      await api.post('/rule-generator/clear');
      setGenerated(false);
      setRules([]);
      setStats({ total_rules: 0, columns_covered: 0, dq_dimensions: 0 });
    } catch (e) { setErr(e?.response?.data?.detail || 'Failed'); }
    finally { setBusy(false); }
  };

  const downloadBlob = async (path, defaultName) => {
    try {
      const res = await api.post(path, null, { responseType: 'blob' });
      const cd = res.headers['content-disposition'] || '';
      const m = cd.match(/filename="?([^"]+)"?/);
      const filename = m ? m[1] : defaultName;
      const url = URL.createObjectURL(new Blob([res.data]));
      const a = document.createElement('a');
      a.href = url; a.download = filename; a.click();
      URL.revokeObjectURL(url);
    } catch (e) {
      setErr(e?.response?.data?.detail || 'Export failed');
    }
  };

  const sourceColors = (val) => {
    if (val === 'Rules from Existing Sheet') return { bg: '#dcfce7', fg: '#166534' };
    if (val === 'Generated by AI') return { bg: '#dbeafe', fg: '#1e40af' };
    return { bg: 'transparent', fg: 'inherit' };
  };

  if (!state.loaded) {
    return (
      <>
        <PageHeader title="Rule Generator" subtitle="AI-Powered Validation Rule Generation" />
        <Alert severity="warning">Please load data first before generating rules.</Alert>
        <Alert severity="info" sx={{ mt: 1 }}>Go to the 'Load Data' tab and upload your file.</Alert>
        <Box sx={{ mt: 2 }}><EmptyState /></Box>
      </>
    );
  }

  if (llm && !llm.configured) {
    return (
      <>
        <PageHeader title="Rule Generator" subtitle="AI-Powered Validation Rule Generation" />
        <Alert severity="error">
          Azure OpenAI not configured. Missing: {(llm.missing || []).join(', ')}
        </Alert>
        <Alert severity="info" sx={{ mt: 1 }}>
          Please set these in your secrets file <code>.streamlit/secrets.toml</code>:
        </Alert>
        <Paper sx={{ mt: 2, p: 2, fontFamily: 'monospace', fontSize: '0.85rem' }}>
{`[default]
AZURE_OPENAI_ENDPOINT = "https://your-resource.openai.azure.com/"
AZURE_OPENAI_KEY = "your-api-key"
AZURE_OPENAI_DEPLOYMENT = "gpt-4o-mini"
AZURE_OPENAI_API_VERSION = "2024-12-01-preview"
AZURE_OPENAI_MAX_RPM = 60`}
        </Paper>
      </>
    );
  }

  return (
    <>
      <PageHeader title="Rule Generator" subtitle="AI-Powered Validation Rule Generation" />

      <Grid container spacing={2} sx={{ mb: 2 }}>
        <Grid item xs={12} md={4}>
          {!generated ? (
            <Button fullWidth size="large" variant="contained" startIcon={<AutoAwesomeIcon />}
              onClick={generate} disabled={busy}>
              {busy ? 'Analyzing data with comprehensive engine…' : 'Generate AI Validation Rules'}
            </Button>
          ) : (
            <Alert severity="success" sx={{ height: '100%' }}>Rules Generated</Alert>
          )}
        </Grid>
        <Grid item xs={12} md={4}>
          {generated && (
            <Button fullWidth size="large" variant="outlined" startIcon={<RefreshIcon />}
              onClick={regenerate} disabled={busy}>Regenerate Rules</Button>
          )}
        </Grid>
        <Grid item xs={12} md={4}>
          {generated && (
            <Button fullWidth size="large" variant="outlined" color="error"
              startIcon={<DeleteIcon />} onClick={clear} disabled={busy}>Clear Rules</Button>
          )}
        </Grid>
      </Grid>

      {busy && <LinearProgress sx={{ mb: 2 }} />}
      {err && <Alert severity="error" sx={{ mb: 2 }}>{err}</Alert>}

      <Divider sx={{ my: 2 }} />

      {generated && rules.length > 0 ? (
        <>
          <Grid container spacing={2} sx={{ mb: 2 }}>
            <Grid item xs={4}><MetricCard label="Total Rules" value={stats.total_rules} /></Grid>
            <Grid item xs={4}><MetricCard label="Columns Covered" value={stats.columns_covered} /></Grid>
            <Grid item xs={4}><MetricCard label="DQ Dimensions" value={stats.dq_dimensions} /></Grid>
          </Grid>

          <Divider sx={{ my: 2 }} />

          <Typography variant="h6" gutterBottom>Data Quality Rules</Typography>
          <TableContainer component={Paper} sx={{ maxHeight: 700 }}>
            <Table stickyHeader size="small">
              <TableHead>
                <TableRow>
                  <TableCell sx={{ fontWeight: 600 }}>S.No</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Column</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Business Field</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Rule Source</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Dimension</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Data Quality Rule</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Regex Pattern</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Issues Found</TableCell>
                  <TableCell sx={{ fontWeight: 600 }}>Issues Found Example</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {rules.map((r, i) => {
                  const issues = Number(r['Issues Found']) || 0;
                  const example = String(r['Issues Found Example'] || '');
                  let exampleStyle = {};
                  if (example.startsWith('All values valid')) {
                    exampleStyle = { bgcolor: '#dcfce7', color: '#166534', fontSize: '0.78rem' };
                  } else if (example) {
                    exampleStyle = { bgcolor: '#fef3c7', color: '#92400e', fontSize: '0.78rem' };
                  }
                  const src = sourceColors(r['Rule Source']);
                  return (
                    <TableRow key={i}>
                      <TableCell>{r['S.No']}</TableCell>
                      <TableCell>{r['Column']}</TableCell>
                      <TableCell>{r['Business Field']}</TableCell>
                      <TableCell sx={{ bgcolor: src.bg, color: src.fg, fontWeight: 700 }}>
                        {r['Rule Source']}
                      </TableCell>
                      <TableCell sx={{
                        bgcolor: DIMENSION_BG[r.Dimension] || 'transparent',
                        color: DIMENSION_FG[r.Dimension] || 'inherit',
                        fontWeight: r.Dimension === 'Character Length' ? 700 : 600,
                      }}>
                        {r.Dimension}
                      </TableCell>
                      <TableCell sx={{ fontSize: '0.85rem' }}>{r['Data Quality Rule']}</TableCell>
                      <TableCell sx={{ fontFamily: 'monospace', fontSize: '0.75rem',
                                       maxWidth: 220, wordBreak: 'break-all' }}>
                        {r['Regex Pattern'] || ''}
                      </TableCell>
                      <TableCell sx={issues > 0
                        ? { bgcolor: '#fee2e2', color: '#991b1b', fontWeight: 700 }
                        : {}}>
                        {issues}
                      </TableCell>
                      <TableCell sx={{ ...exampleStyle, maxWidth: 320, wordBreak: 'break-word' }}>
                        {example}
                      </TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          </TableContainer>
          <Typography variant="caption" color="text.secondary" sx={{ mt: 1, display: 'block' }}>
            Showing {rules.length} rules
          </Typography>

          <Divider sx={{ my: 3 }} />

          <Typography variant="h6" gutterBottom>Export Rules</Typography>
          <Stack direction={{ xs: 'column', md: 'row' }} spacing={2} sx={{ maxWidth: 700 }}>
            <Button variant="outlined" startIcon={<DownloadIcon />}
              onClick={() => downloadBlob('/rule-generator/export/excel', 'rules.xlsx')}>
              Download as Excel
            </Button>
            <Button variant="outlined" startIcon={<DownloadIcon />}
              onClick={() => downloadBlob('/rule-generator/export/pdf', 'rules.pdf')}>
              Download DQ Report PDF
            </Button>
          </Stack>
        </>
      ) : (
        !busy && (
          <Alert severity="info">Click 'Generate AI Validation Rules' to start</Alert>
        )
      )}
    </>
  );
}
